# Generated by Django 5.0.6 on 2024-07-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
