# Generated by Django 5.0.6 on 2024-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_image_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval')], default='pending', max_length=10),
        ),
    ]
