# Generated by Django 5.0.6 on 2024-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='purchase_status',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('not_purchased', 'Not Purchased')], default='not_purchased', max_length=15),
        ),
    ]
