# Generated by Django 5.0.6 on 2024-07-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_donation_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/donated/additional/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.donation')),
            ],
        ),
    ]
