# Generated by Django 5.0.6 on 2024-07-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
