# Generated by Django 5.0.6 on 2024-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_breed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
